name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  # OnePlus 8 (OxygenOS 13.1)
  build-oneplus-8-oos13-a13:
    name: "OnePlus 8 (OxygenOS 13.1 Android 13) (Stock)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-oneplus-8-oos13.1.yml
    secrets: inherit
